'use stict';

export const actionTypes = {
   SET_PRODUCTS : 'SET_PRODUCTS',
   SET_CATEGORY : 'SET_CATEGORY',
   SET_ACTIVECATEGORY : 'SET_ACTIVECATEGORY',
   ADD_TO_CART : 'ADD_TO_CART',
   DELETE_FROM_CART : ' DELETE_FROM_CART'
}